In [1]:
import numpy as np

In [3]:
revenue= np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [6]:
taka = np.array(revenue * 105)
taka

array([[21000, 23100, 26250],
       [ 7140,  8295, 11025],
       [11550, 14700, 18900],
       [ 8400,  8925,  9450]])

In [7]:
units = np.array([[50,60,25],[10,13,5],[40,70,52]])
units

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [8]:
price_per_unit = np.array([[20],[30],[15]])
price_per_unit

array([[20],
       [30],
       [15]])

In [ ]:
total = np.array(price_per_unit * units )
monthly_sales = total.sum(axis=0)
monthly_sales

array([1900, 2640, 1430])